version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000 # test ortamı
    # command: gunicorn common.wsgi:application --bind 0.0.0.0:8000
    restart: 'no'
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run serve
    restart: 'no'
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  db:
    image: postgres:13.0-alpine
    restart: 'no'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=basic_django
      - POSTGRES_PASSWORD=basic_django
      - POSTGRES_DB=basic_django_dev

volumes:
  postgres_data: